'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH credential-sheets 1 "Sep 2016" "Version 0.0.2" "User Account Credentials Tool"
.SH NAME
credential-sheets \- Account Credential Sheets Tool
.SH SYNOPSIS
'nh
.fi
.ad l
\fBcredential-sheets\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[
\fI[options] <CSV-file-1> [<CSV-file-2> [...]]\fR
]
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
After mass import of user accounts (e.g. into LDAP) most site
administrators have to create information sheets (or snippets) containing
those new  credentials (like username, password, policy of usage, etc.).
.PP
With this tiny tool, providing these pieces of information to multiple
users, becomes really simple. Account data is taken from a CSV file and
the sheets are output as PDF using easily configurable LaTeX template
files.

.SH OPTIONS
\fBcredential-sheets\fR command accepts the following command-line options:
.TP
\*(T<\fB\-\-help\fR\*(T>
Display a help with all available command line options and exit.
.TP
\*(T<\fB\-\-template=<tpl-name>\fR\*(T>
Name of the template to use.
.TP
\*(T<\fB\-\-cols=<x>\fR\*(T>
Render <x> columns per sheet.
.TP
\*(T<\fB\-\-rows=<y>\fR\*(T>
Render <y> rows per sheet.
.TP
\*(T<\fB\-\-zip\fR\*(T>
Do create a ZIP file at the end.
.TP
\*(T<\fB\-\-zipfilename=<zip-file-name>\fR\*(T>
Alternative ZIP file name (default: name of parent folder).
.TP
\*(T<\fB\-\-debug\fR\*(T>
Don't remove temporary files.

.SH CSV FILE FORMAT
The \fBcredential-sheets\fR tool can handle any sort of column arrangement
in given CSV file(s). It expects the CSV file(s) to have column names in
their first line.
.PP
The given column names have to map to the "VAR-<column-name>"
placeholders in \fBcredential-sheets\fR's LaTeX templates.
.PP
The shipped-with templates "students" and "teachers" can handle these
column names:
.PP
  * \fBlogin\fR -- The user account's login id (uid)
  * \fBlastName\fR -- The user's last name(s)
  * \fBfirstName\fR -- The user's first name(s)
  * \fBpassword\fR -- The user's password
  * \fBform\fR -- The form name/ID (student template only)
  * \fBsubjects\fR -- A list of subjects taught by a teacher (teacher
    template only)
.PP
The shipped-with template "wifivouchers" can handle these column names:
.PP
  * \fBessid\fR \-\- The WiFi network's ESSID (network name)
  * \fBlogin\fR \-\- The voucher\'s login id (if any)
  * \fBcode\fR \-\- The voucher\'s login code
  * \fBduration\fR \-\- The validity period of a voucher code
.PP
If you create your own templates, you can be very flexible in using your
own column names and template names. Only make sure that the column names
provided in the CSV file(s)'s first line match the variables used in the
customized LaTeX template. See below for details.

.SH CUSTOMIZATIONS

The shipped-with credential sheets templates are expected to be installed
in ``/usr/share/credential-sheets/`` for system-wide installations. When
customizing templates, simply place a modified copy of any of those files
into ``~/.credential-sheets/`` or ``/etc/credential-sheets/``. For
further details, see below.
.PP
The \fBcredential-sheets\fR tool uses these *configuration* files:
.PP
  * \fIheader.tex\fR (LaTeX file header)
  * \fI<tpl-name>-template.tex\fR (where as \fI<tpl-name>\fR "students" and
    "teachers" is provided on default installations, this is extensible
    by defining your own template files, see below).
  * \fIfooter.tex\fR (LaTeX file footer)
.PP
Search paths for configuration files (in listed order):
.PP
  * \fI$HOME/.credential-sheets/\fR
  * \fI./\fR
  * \fI/etc/credential-sheets/\fR
  * \fI/usr/local/share/credential-sheets/\fR
  * \fI/usr/share/credential-sheets/\fR
.PP
You can easily customize the resulting PDF files generated with this tool
by placing your own template files, header and footer where appropriate.
.PP

.SH FILES
\fB/usr/share/credentail-sheets/*.tex\fR

\fB/etc/credential-sheets/*.tex\fR (optional)

\fB$HOME/.credential-sheets/*.tex\fR (optional)

.SH AUTHOR
This manual and the \fBcredential-sheets\fR tool itself has been written for the Debian Edu project by
Mike Gabriel <mike.gabriel@das-netzwerkteam.de>.

